### ISSUE TITLE
[Chasing Ghosts] Bomb Jack - 300320

### ISSUE THREAD

**Issue by phoenity** [PixelsCamp/challenges#1]
(I can't label if not a contributor to the project it seems)

The shot:
![screen shot 2016-09-20 at 00 57 48](https://cloud.githubusercontent.com/assets/44125/18653185/2ccaafcc-7ed0-11e6-9985-6d657c0e8d58.png)

Verification:
![img_8497](https://cloud.githubusercontent.com/assets/44125/18653192/3ab38cd0-7ed0-11e6-8459-64cc73aefb0f.JPG)

**Comment by celso** [comment]
Game on
